apiVersion: v1
kind: PersistentVolume
metadata:
  name: fire-pv
spec:
 capacity:
   storage: 10Gi
accessModes:
  - ReadWriteOnce
persistentVolumeReclaimPolicy: Retain
storageClassName: standard
hostPath:
  path: /data/fire

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: fire-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
