apiVersion: v1
kind: Secret
metadata:
  name: sparkflows-db-secret
  namespace: sparkflows
type: Opaque
data:
  KEYSTORE_PASSWORD: MTIzNDU2Nzg=
  DB_HOST: MTAuOTguMzIuMjE5
  DB_USERNAME: ZmlyZQ==
  DB_PASSWORD: cGFzc3cwcmQ=
  DB_PORT: MzMwNg==
