apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkflows-app
  labels:
    app: sparkflows-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkflows-app
  template:
    metadata:
      labels:
        app: sparkflows-app
    spec:
      serviceAccountName: default
      volumes:
        - name: sparkflows-vol
          persistentVolumeClaim:
            claimName: fire-pvc
      containers:
        - name: sparkflows-fire
          image: "sparkflows/fire:py_3.2.1_3.2.81-rc1"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "4"
              memory: "16Gi"
            requests:
              cpu: "2"
              memory: "8Gi"
          volumeMounts:
            - name: sparkflows-vol
              mountPath: /root
          env:
            - name: KEYSTORE_PASSWORD
              value: "12345678"

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8080
