apiVersion: v1
kind: Service
metadata:
  name: sparkflows-app
  labels:
    app: sparkflows-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sparkflows-app
