apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-creator
rules:
- apiGroups: ["batch",""]
  resources:
  - jobs
  - pods
  - pods/log
  verbs:
  - create
  - get
  - update
  - watch
  - list
  - delete
